const express = require('express');
const app = express();

// Dados fictícios das flores
const Flora = [
  {id: 1, imagem: 'https://p2.trrsf.com/image/fget/cf/940/0/images.terra.com/2022/07/01/1451421885-15-tipos-de-lavanda-para-perfumar-seu-jardim-gardeningetc-kernock-park-plants.jpg', nome:'Lavanda', origem:'A lavanda é nativa das regiões montanhosas da Europa ao redor do Mediterrâneo, incluindo países como França, Espanha, Itália e Croácia. É conhecida por suas flores roxas e aroma relaxante', categoria: 'Planta', solo: 'A lavanda prefere solos bem drenados, arenosos ou calcários. Evite solos muito úmidos, pois a planta é suscetível ao apodrecimento das raízes.',
    localizacao: "Plante a lavanda em um local que receba pelo menos 6 horas de sol direto por dia.", irrigacao: ' Regue moderadamente, permitindo que o solo seque entre as regas. A lavanda é resistente à seca uma vez estabelecida.', adubacao: 'Utilize um fertilizante balanceado, preferencialmente orgânico, que seja de liberação lenta. O adubo deve ser baixo em nitrogênio e mais rico em fósforo e potássio, pois isso favorece a floração.', podas: ' Realize podas regulares após a floração para manter a planta compacta e incentivar novas flores.',
    curiosidade:'Além de ser amplamente utilizada em jardins ornamentais, a lavanda tem várias aplicações medicinais e cosméticas, como em chás, infusões, óleos e sachês aromáticos.'
  },

  {id: 2, imagem: 'https://img.freepik.com/fotos-premium/rosas-de-jardim-roseira-flores-cor-de-rosa-no-jardim_156843-552.jpg', nome:'Rosa ', origem:'As rosas têm uma origem diversificada, mas a maioria das espécies é nativa da Ásia. Algumas espécies também são encontradas na Europa, América do Norte e África. São amplamente cultivadas por suas flores belas e perfumadas', categoria: 'Planta', solo: 'As rosas preferem solos bem drenados e ricos em matéria orgânica. Adicione compostagem ou esterco bem decomposto ao solo para melhorar a fertilidade.',
    localizacao: 'Plante as rosas em um local que receba pelo menos 6 horas de sol direto por dia. Elas se desenvolvem melhor em áreas com boa circulação de ar.', irrigacao: ' Regue as rosas regularmente, mantendo o solo úmido mas não encharcado. Evite molhar as folhas para prevenir doenças fúngicas.', adubacao: 'Fertilize regularmente durante a estação de crescimento, utilizando um fertilizante específico para rosas ou um fertilizante balanceado.', curiosidade: 'Além de sua beleza ornamental, as pétalas de algumas espécies de rosas são utilizadas em cosméticos, perfumes e produtos medicinais, como águas florais e óleos essenciais.'
  },

  {id: 3, imagem: 'https://casa.abril.com.br/wp-content/uploads/2021/09/Como-plantar-e-cuidar-de-horte%CC%82nsias-10.jpg?crop=1&resize=1212,909', nome:'Hortênsia', origem:'As hortênsias são nativas do sul e leste da Ásia, particularmente Japão, China e Himalaia. Elas são populares por suas grandes inflorescências que podem ser de várias cores, incluindo azul, rosa, branco e roxo', categoria: 'Planta', solo: 'Preferem solos ricos em matéria orgânica, bem drenados e levemente ácidos. A acidez do solo pode influenciar a cor das flores.',
    localizacao: 'Idealmente, devem ser plantadas em áreas que recebam sol da manhã e sombra à tarde. Em climas mais frios, elas podem tolerar mais sol.', irrigacao: 'Mantenha o solo úmido, mas não encharcado. Hortênsias precisam de rega regular, especialmente durante períodos secos.', adubacao: 'Use um fertilizante balanceado (10-10-10) ou um específico para hortênsias. Para alterar a cor das flores, adubos contendo alumínio (para flores azuis) ou calcário (para flores rosas) podem ser usados.', curiosidade:'As flores da hortênsia podem ser de várias cores, incluindo azul, rosa, branco e roxo, dependendo da variedade e do pH do solo. As inflorescências podem ser esféricas ou em formato de cone.'
  },

  {id: 4, imagem: 'https://imagens-revista.vivadecora.com.br/uploads/2019/11/crisantemo.jpg', nome:'Crisântemo', origem:'Originário da China, o crisântemo tem sido cultivado há mais de 2.500 anos. Também é popular no Japão, onde simboliza o sol e é uma flor nacional. As flores vêm em uma variedade de cores e formas', categoria: 'Planta', solo:' Prefere solos bem drenados, ricos em matéria orgânica. A adição de compostagem pode melhorar a qualidade do solo.', localizacao: 'Plante em um local que receba pelo menos 6 horas de sol direto por dia para estimular a floração.',
    irrigacao:'Regue regularmente para manter o solo uniformemente úmido, mas não encharcado. Evite molhar as folhas para prevenir doenças fúngicas.', adubacao:"Utilize um fertilizante balanceado (20-10-20) ou um específico para flores. Fertilizantes com maior teor de fósforo são recomendados para incentivar a floração.", curiosidade:'No Japão, o crisântemo é um símbolo do sol e é associado à longevidade e rejuvenescimento. Na China, eles são símbolos de vida e morte, frequentemente usados em cerimônias e festividades.'
  },

  {id: 5, imagem: 'https://blog.cobasi.com.br/wp-content/uploads/2023/02/jasmim-capa.png', nome:'Jasmim', origem:'O jasmim é nativo das regiões tropicais e subtropicais da Eurásia, Australásia e Oceania. É altamente valorizado pelo seu perfume doce e é usado em perfumes e chás', categoria: 'Planta', solo:' Prefere solos bem drenados e ricos em matéria orgânica. Adicione compostagem ou esterco bem decomposto para melhorar a fertilidade do solo.', localizacao:' Plante o jasmim em um local que receba pleno sol ou sombra parcial. Ele precisa de pelo menos 4 a 6 horas de sol direto por dia para florescer bem.', irrigacao:' Mantenha o solo consistentemente úmido, mas evite encharcá-lo. Regue regularmente, especialmente durante períodos secos.',
    adubacao:'Utilize um fertilizante balanceado (10-10-10) ou um específico para plantas floríferas. Fertilizantes ricos em fósforo são ideais para estimular a floração regurlamente durante sua estação de crescimento.', curiosidade:" Em muitas culturas, o jasmim é associado à pureza, beleza e amor. Ele é frequentemente usado em cerimônias e como ornamento em eventos festivos."
  },

  {id: 6, imagem: 'https://i0.wp.com/revistajardins.pt/wp-content/uploads/2019/03/ThinkstockPhotos-126994221.jpg?fit=1080%2C719&ssl=1', nome:'Hibisco', origem:'O hibisco é originário de regiões tropicais e subtropicais ao redor do mundo, especialmente do sudeste da Ásia e das ilhas do Pacífico. As flores são grandes, vistosas e vêm em várias cores brilhantes', categoria: 'Planta', solo: 'Prefere solos bem drenados, ricos em matéria orgânica e ligeiramente ácidos. Melhorar o solo com compostagem pode ajudar no crescimento saudável da planta.', localizacao: 'Plante em um local que receba pleno sol. O hibisco precisa de pelo menos 6 horas de sol direto por dia para florescer profusamente.',
    irrigacao: "Mantenha o solo constantemente úmido, mas não encharcado. Durante períodos secos ou quentes, aumente a frequência das regas.", adubacao: "Utilize um fertilizante balanceado (20-10-20) ou um específico para plantas floríferas. Fertilizantes com maior teor de potássio são benéficos para a floração, adube regurlamente durante seu cresimento.", curiosidade: "Algumas espécies de hibisco são usadas na medicina tradicional para tratar várias condições de saúde, e suas flores são frequentemente usadas para fazer chá de hibisco, conhecido por seus potenciais benefícios à saúde."
  },

  {id: 7, imagem: 'https://s2.glbimg.com/nijmMyiGE-SdhZpLlNMOYI1Z6Ts=/620x413/smart/e.glbimg.com/og/ed/f/original/2021/12/12/saiba-como-cultivar-margaridas-no-seu-vaso-ou-jardim_3.jpg', nome:'Margarida', origem:'A margarida é nativa da Europa e é amplamente distribuída em todo o continente. É conhecida por suas flores brancas com centros amarelos e simboliza pureza e inocência', categoria: 'Planta', solo:"Prefere solos bem drenados e férteis. A adição de composto ou matéria orgânica pode melhorar a qualidade do solo.", localizacao:"Plante em um local que receba pleno sol a sombra parcial. As margaridas florescem melhor com pelo menos 6 horas de luz solar direta por dia.",
    irrigacao:"Mantenha o solo uniformemente úmido, especialmente durante os períodos de crescimento ativo e floração. Evite o excesso de água para prevenir o apodrecimento das raízes.", adubacao:"Use um fertilizante balanceado (10-10-10) ou específico para plantas com flores.", curiosidade:"As margaridas são amplamente cultivadas em jardins, canteiros e vasos. São ideais para bordaduras e combinam bem com outras plantas de flores. Além de sua beleza ornamental, as margaridas também são usadas simbolicamente em arranjos florais para representar pureza e inocência."
  },

  {id: 8, imagem: 'https://s2-casaejardim.glbimg.com/GPsKoVm05e08EjvK74gyn6j6d4E=/0x0:1400x933/924x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_a0b7e59562ef42049f4e191fe476fe7d/internal_photos/bs/2023/T/0/ttTFJTRMW375dww7RH1Q/petunia-flor-como-cultivar-sol-cuidar-plantar-dicas-casa-e-jardim-paisagismo.jpg', nome:'Petúnia', origem:'As petúnias são nativas da América do Sul, especialmente do Brasil e Argentina. Elas são populares em jardins devido à sua ampla gama de cores vibrantes e à facilidade de cultivo', categoria: 'Planta', solo:"Prefere solos bem drenados e ricos em matéria orgânica. Melhorar o solo com composto ou turfa pode ser benéfico.", localizacao:"Plante em um local que receba pleno sol. As petúnias necessitam de pelo menos 6 horas de luz solar direta por dia para florescerem abundantemente.",
    irrigacao:" Mantenha o solo uniformemente úmido, mas evite o excesso de água. Regue regularmente, especialmente durante períodos de seca, mas deixe o solo secar um pouco entre as regas para prevenir o apodrecimento das raízes.", adubacao:"Use um fertilizante balanceado (10-10-10) ou específico para plantas com flores.", curiosidade:"As petúnias são amplamente cultivadas em jardins, canteiros, vasos e cestas suspensas. Elas são ideais para bordaduras e como plantas de cobertura de solo, bem como para adicionar cores vibrantes a espaços de jardinagem vertical."
  },

  {id: 9, imagem: 'https://s2.glbimg.com/STk3HRkXzTOUdTITwAssKl8mbaU=/620x455/e.glbimg.com/og/ed/f/original/2020/07/24/800px-begonia_semperflorens_dark_pink_01.jpg', nome:'Begônia', origem:'As begônias são originárias das regiões tropicais e subtropicais da América do Sul, África e Ásia. Elas são conhecidas por suas flores coloridas e folhas ornamentais', categoria: 'Planta', solo:" Prefere solos bem drenados e ricos em matéria orgânica. Um solo ligeiramente ácido a neutro (pH 5.5 a 6.5) é ideal.", localizacao:"Plante em um local com sombra parcial a sombra total. As begônias não toleram luz solar direta intensa, que pode queimar suas folhas.",
    irrigacao:"Mantenha o solo uniformemente úmido, mas evite o encharcamento. Regue regularmente, mas permita que a camada superior do solo seque entre as regas para prevenir o apodrecimento das raízes.", adubacao:"Use um fertilizante balanceado (10-10-10) ou específico para plantas com flores.", curiosidade:"As begônias são amplamente cultivadas em jardins, canteiros, vasos e cestas suspensas. Elas são ideais para bordaduras e como plantas de cobertura de solo, bem como para adicionar cores vibrantes a áreas sombreadas do jardim."
  },

  {id: 10, imagem: 'https://www.sitiodamata.com.br/media/catalog/product/cache/80281f1a4d89199560fc0837e49d13da/s/e/semente-alecrim-rosmarinho-rosmarinus-officinalis_2nd.jpg', nome:'Alecrim', origem:'O alecrim é nativo da região do Mediterrâneo, incluindo países como Espanha, Portugal, Marrocos e Tunísia. É uma erva perene amplamente usada na culinária, além de ter propriedades medicinais e um aroma agradável', categoria: 'Planta', solo:" Prefere solos bem drenados, arenosos ou argilosos, e levemente alcalinos. O solo não precisa ser especialmente rico em matéria orgânica.", localizacao:"Plante em um local que receba pleno sol. O alecrim necessita de pelo menos 6 horas de luz solar direta por dia para crescer vigorosamente.",
    irrigacao:"Regue moderadamente, permitindo que o solo seque entre as regas. O alecrim é tolerante à seca e não gosta de solo encharcado, que pode levar ao apodrecimento das raízes.", adubacao:"Use um fertilizante balanceado (10-10-10) ou específico para ervas, mas em quantidade moderada.", curiosidade:"O alecrim é amplamente usado na culinária para temperar carnes, sopas, pães e outros pratos. Também é utilizado em chás, óleos essenciais e produtos medicinais devido às suas propriedades antioxidantes e anti-inflamatórias."
  },

  {id: 11, imagem: 'https://pergunteaoagronomo.com.br/wp-content/uploads/2023/05/Gardening-Know-How.webp', nome:'Tomate', origem:'O tomate é nativo da América do Sul, mais precisamente da região que hoje corresponde ao Peru e ao Equador. Foi domesticado e cultivado pelos povos indígenas antes de ser levado para a Europa pelos exploradores espanhóis no século XVI', categoria:'Semente', solo:' Prefere solos bem drenados, ricos em matéria orgânica e com pH levemente ácido (6.0 a 6.8). Adicione compostagem para melhorar a fertilidade do solo.', localizacao: 'Plante em um local que receba pelo menos 6 a 8 horas de sol direto por dia.',
    irrigacao: 'Mantenha o solo uniformemente úmido, mas não encharcado. Regue na base da planta para evitar molhar as folhas e reduzir o risco de doenças.', adubacao: 'Use um fertilizante balanceado (10-10-10) ou específico para tomates, que são ricos em fósforo e potássio para promover a floração e a frutificação.', curiosidade: " Os frutos do tomateiro podem variar em forma, tamanho e cor, incluindo vermelho, amarelo, laranja, verde e roxo. Eles são ricos em vitaminas A e C, além de antioxidantes como o licopeno."
  },

      {id: 12, imagem: 'https://starfoods.vn/wp-content/uploads/2018/05/bi-ngo-la-loai-cay-quen-thuoc-trong-doi-song-hang-ngay.jpg', nome:'Abóbora', origem:'A abóbora é originária das Américas, especialmente da América Central e do Norte. Era cultivada pelos povos indígenas muito antes da chegada dos europeus e fazia parte da dieta básica junto com o milho e o feijão', categoria:'Semente', solo:'Prefere solos bem drenados, ricos em matéria orgânica e com pH neutro a ligeiramente ácido (6.0 a 6.8). A adição de compostagem ou esterco bem decomposto pode melhorar a qualidade do solo.', localizacao:'Plante em um local que receba pleno sol, com pelo menos 6 a 8 horas de sol direto por dia.',
        irrigacao:'Mantenha o solo constantemente úmido, especialmente durante a formação dos frutos. Evite molhar as folhas para reduzir o risco de doenças.', adubacao:'Utilize um fertilizante balanceado (10-10-10) ou rico em fósforo e potássio, que são essenciais para a floração e frutificação.', curiosidade:" A abóbora é utilizada de diversas maneiras na culinária, incluindo sopas, purês, tortas, pães e como vegetais assados. As sementes também podem ser torradas e consumidas como um lanche nutritivo."
      },

      {id: 13, imagem: 'https://pergunteaoagronomo.com.br/wp-content/uploads/2023/08/melancia-capa-otimizado.webp', nome:'Melancia', origem:'A melancia é originária da África, onde crescia selvagem. Foi domesticada pelos antigos egípcios há mais de 4.000 anos e, a partir daí, se espalhou pelo Mediterrâneo e pelo resto do mundo', categoria:'Semente', solo:"Prefere solos bem drenados, ricos em matéria orgânica, e com pH levemente ácido a neutro (6.0 a 7.0). Melhorar o solo com compostagem ajuda a fornecer os nutrientes necessários.", localizacao:"Plante em um local que receba pleno sol, com pelo menos 6 a 8 horas de luz solar direta por dia.",
        irrigacao:"Mantenha o solo uniformemente úmido, especialmente durante a formação dos frutos. Evite molhar as folhas para reduzir o risco de doenças. Diminua a irrigação à medida que os frutos se aproximam da maturidade para melhorar o sabor.", adubacao:"Utilize um fertilizante balanceado (10-10-10) ou rico em fósforo e potássio, que são essenciais para a floração e frutificação."
      },

      {id: 14, imagem: 'https://fazfacil.com.br/wp-content/uploads/2021/08/20210809-pcdst.jpg', nome:'Cenoura', origem:'A cenoura é originária da região da Pérsia (atual Irã e Afeganistão). Inicialmente cultivada por suas folhas e semente aromáticas, a raiz como a conhecemos hoje foi desenvolvida na Europa por volta do século X', categoria:'Semente', solo:"Prefere solos soltos, bem drenados e arenosos, com pH levemente ácido a neutro (6.0 a 6.8). Evite solos pesados e compactados, pois eles dificultam o crescimento das raízes.", localizacao:"Plante em um local que receba pleno sol, com pelo menos 6 horas de luz solar direta por dia.",
        irrigacao:"Mantenha o solo uniformemente úmido, especialmente durante a germinação e o crescimento inicial das raízes. Evite encharcar o solo para prevenir doenças.", adubacao:"Use um fertilizante balanceado (10-10-10) ou rico em fósforo e potássio. Evite excesso de nitrogênio, pois isso pode levar a um crescimento excessivo das folhas em detrimento das raízes.", curiosidade: "As cenouras produzem flores brancas em forma de umbela no segundo ano de crescimento, se não forem colhidas.As raízes são geralmente longas e cônicas, variando em cor de laranja, amarelo, roxo, vermelho a branco. Elas são ricas em betacaroteno (provitamina A), fibras, vitaminas e minerais."
      },

      {id: 15, imagem: 'https://blog.aegro.com.br/wp-content/uploads/2019/03/plantacao-de-milho.jpg', nome:'Milho', origem:'O milho é nativo das Américas, especialmente do México. Era uma cultura fundamental para os povos indígenas da América do Norte, Central e do Sul muito antes da chegada dos europeus', categoria:'Semente', solo:"Prefere solos férteis, bem drenados e ricos em matéria orgânica, com pH levemente ácido a neutro (6.0 a 6.8). É importante preparar o solo com compostagem ou esterco bem decomposto.", localizacao:"Plante em um local que receba pleno sol, com pelo menos 6 a 8 horas de luz solar direta por dia.",
        irrigacao:"Mantenha o solo uniformemente úmido, especialmente durante a germinação e o crescimento inicial. Evite o encharcamento, pois pode prejudicar as raízes.", adubacao:"Use um fertilizante balanceado (10-10-10) ou específico para culturas de grãos, rico em nitrogênio para promover o crescimento inicial, seguido de fósforo e potássio para o desenvolvimento das espigas.", curiosidade:"As espigas de milho são formadas por grãos dispostos em fileiras, cobertos por folhas protetoras (palhas). Os grãos podem ser amarelos, brancos, vermelhos, azuis ou uma combinação de cores."
      },

      {id: 16, imagem: 'https://static.vecteezy.com/ti/fotos-gratis/p2/11571140-feijao-de-jardim-phaseolus-vulgaris-na-terra-velha-ao-lado-de-hamburgo-foto.jpg', nome:'Feijão', origem:'O feijão é originário da América Central e do Sul, onde foi cultivado por milhares de anos pelos povos indígenas. É uma das plantas mais antigas a serem domesticadas na América', categoria:'Semente', solo:"Prefere solos bem drenados, férteis e ricos em matéria orgânica. Um pH neutro a ligeiramente ácido é ideal (6.0-6.8).", localizacao:"Plante em um local que receba pelo menos 6 horas de sol direto por dia. O feijão gosta de calor e luz solar para um crescimento saudável.",
        irrigacao:"Mantenha o solo uniformemente úmido, mas não encharcado. Regue regularmente, especialmente durante períodos de seca.", adubacao:"Durante o crescimento, utilize um fertilizante balanceado, rico em fósforo e potássio (por exemplo, NPK 10-10-10), aplicado conforme as recomendações da embalagem.", curiosidade:"Existem várias variedades de feijão, incluindo feijão-preto, feijão-verde, feijão-fradinho, entre outros, cada um com suas próprias características de sabor e uso culinário."
      },

      {id: 17, imagem: 'https://imagens-revista.vivadecora.com.br/uploads/2018/09/Girassol-em-jardins.jpg', nome:'Girassol', origem:'O girassol é originário da América do Norte, onde foi cultivado pelos nativos americanos há mais de 4.000 anos. Eles usavam a planta para alimentos, óleo e como elemento decorativo', categoria:'Semente', solo:"Prefere solos bem drenados e ricos em matéria orgânica. Tolera solos levemente ácidos a alcalinos (pH 6.0-7.5)."  ,localizacao:"Plante em um local que receba pelo menos 6-8 horas de luz solar direta por dia. O girassol é conhecido por seguir o movimento do sol (heliotropismo).",
        irrigacao:" Regue profundamente, especialmente durante o período de crescimento ativo, mas evite encharcar o solo.", adubacao:"Antes do plantio, adicione composto orgânico ao solo para fornecer nutrientes essenciais.", curiosidade:"Além de seu apelo estético em jardins e paisagens, o girassol é cultivado comercialmente para a produção de óleo comestível e como fonte de sementes nutritivas."
      },

      {id: 18, imagem: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScRHVUs_sMI3lf7Mz8UxZEUCO4ofhB1NniNZjIuNAkAg&s', nome:'Abacate', origem:'O abacate é nativo da América Central e do México. Foi cultivado e utilizado pelos povos mesoamericanos por milhares de anos antes da chegada dos europeus', categoria:'Semente', solo:" Prefere solos bem drenados e ricos em matéria orgânica. O pH ideal do solo para o abacateiro está entre 6,0 e 7,0.", localizacao:"Deve ser plantado em um local com pleno sol, protegido de ventos fortes, especialmente quando jovem.",
        irrigacao:"Regue regularmente, mantendo o solo úmido, mas não encharcado. O abacateiro não tolera solo encharcado por períodos prolongados.", adubacao:"Use um adubo balanceado rico em nitrogênio, fósforo e potássio, adequado para árvores frutíferas.", curiosidade:"Os abacates são amplamente utilizados na culinária, principalmente em saladas, guacamole e como ingrediente em diversos pratos. Eles também são valorizados por suas propriedades nutricionais."
      },

      {id: 19, imagem: 'https://img.myloview.com.br/quadros/maca-vermelha-em-um-ramo-de-arvore-no-jardim-fim-acima-macas-maduras-pendurado-no-galho-no-pomar-colheita-fresca-700-136099781.jpg', nome:'Maçã', origem:'As maçãs são originárias da região do Cazaquistão, na Ásia Central. Acredita-se que a espécie selvagem Malus sieversii seja o ancestral da maçã doméstica', categoria:'Semente', solo:"Prefere solos bem drenados, ricos em matéria orgânica e com pH entre 6,0 e 7,0.", localizacao:"Plante em locais que recebam pelo menos 6 horas de sol direto por dia, essencial para o desenvolvimento saudável da árvore e frutificação.", 
        irrigacao:"As maçãs precisam de água regularmente para manter o solo úmido, especialmente durante os períodos de crescimento ativo e formação dos frutos.", adubacao:"Use um adubo balanceado rico em nitrogênio, fósforo e potássio, formulado para árvores frutíferas.", curiosidade:"Variedades variam em cor e sabor, geralmente vermelhas, verdes ou amarelas. São uma excelente fonte de vitaminas, fibras e antioxidantes."
      },

      {id: 20, imagem: 'https://www.queridasplantas.com/wp-content/uploads/2016/11/Como-plantar-alface.jpg', nome:'Alface', origem:'A alface é originária da região leste do Mediterrâneo e do Oriente Médio. Era cultivada pelos antigos egípcios, gregos e romanos, sendo uma das primeiras plantas a serem cultivadas pelo homem', categoria:'Semente', solo:"Prefere solos bem drenados, ricos em matéria orgânica e com pH entre 6,0 e 7,0.", localizacao:"Plante em locais que recebam luz solar direta por pelo menos 6 horas por dia, mas pode tolerar alguma sombra parcial, especialmente em climas mais quentes.",
        irrigacao:|"Mantenha o solo uniformemente úmido. Evite o encharcamento, pois a alface é suscetível a doenças fúngicas se o solo ficar muito molhado.", adubacao:"Utilize um fertilizante balanceado, rico em nitrogênio para promover o crescimento das folhas.", curiosidade:"Existem muitas variedades de alface, desde as folhas soltas até as variedades de cabeça, como a alface iceberg."
      },

      {id: 21, imagem: 'https://pergunteaoagronomo.com.br/wp-content/uploads/2023/09/The-Plant-Collector-683x1024.webp', nome:'Árvore de Bordo', origem:'As árvores de bordo são nativas das regiões temperadas do Hemisfério Norte, especialmente da América do Norte. São conhecidas por suas folhas que mudam de cor no outono', categoria: 'Arvore', solo:"Prefere solos bem drenados, férteis e ligeiramente ácidos a neutros (pH 6.0 a 7.0). Adicionar matéria orgânica, como composto ou turfa, pode ajudar a melhorar a estrutura do solo.", localizacao:"Plante em um local que receba sol pleno a sombra parcial. A exposição ao sol direto é ideal para a melhor coloração das folhas no outono.",
        irrigacao:" Mantenha o solo uniformemente úmido, especialmente durante os primeiros anos após o plantio. As árvores maduras são mais tolerantes à seca, mas é benéfico regar durante períodos secos prolongados.",  adubacao:"Use um fertilizante balanceado (10-10-10) ou um fertilizante específico para árvores. O adubo deve ser rico em nutrientes essenciais como nitrogênio, fósforo e potássio.", curiosidade:"Além de sua beleza ornamental, algumas espécies de bordo, como o bordo-açucareiro (Acer saccharum), são utilizadas para a produção de xarope de bordo. A madeira de bordo é valorizada para a fabricação de móveis, pisos e instrumentos musicais."
      },

      {id: 22, imagem: 'https://d7cb654846.cbaul-cdnwnd.com/d3e965bb4a19ca659f3ac83e3bc3bf51/system_preview_detail_200000015-9da889ea3b/magn%C3%B3lia.jpg', nome:'Árvore de Magnólia', origem:'As magnólias são nativas da América do Norte, América Central e Ásia. Elas são apreciadas por suas grandes e perfumadas flores que aparecem na primavera', categoria: 'Arvore', solo:"Prefere solos ricos, bem drenados e ligeiramente ácidos a neutros (pH 5.5 a 6.5). Melhorar o solo com matéria orgânica, como composto ou turfa, pode ser benéfico.", localizacao:"Plante em um local que receba sol pleno a sombra parcial. Magnólias precisam de proteção contra ventos fortes que podem danificar as flores.",
        irrigacao:" Mantenha o solo uniformemente úmido, especialmente durante os primeiros anos de estabelecimento. As árvores maduras são mais tolerantes à seca, mas a irrigação regular durante períodos secos é recomendada.", adubacao:"Use um fertilizante balanceado (10-10-10) ou específico para árvores floríferas, rico em fósforo para incentivar a floração.", curiosidade:"As magnólias são amplamente utilizadas como plantas ornamentais em jardins e paisagismo devido à sua beleza e flores perfumadas. Algumas espécies também são valorizadas por sua madeira."
      },

      {id: 23, imagem: 'https://ae01.alicdn.com/kf/S8bd18f3d3afc4465965acb66c26182a7x.jpg_640x640Q90.jpg_.webp', nome:'Árvore de Cerejeira', origem:'As cerejeiras são originárias das regiões temperadas do Hemisfério Norte, especialmente da Ásia e Europa. São famosas pelas flores de cerejeira, especialmente no Japão', categoria: 'Arvore', solo:"Prefere solos bem drenados, férteis e ligeiramente ácidos a neutros (pH 6.0 a 7.0). Melhore o solo com matéria orgânica, como composto, para promover o crescimento vigoroso.", localizacao:"Plante em um local que receba pleno sol para obter o melhor florescimento. A cerejeira precisa de pelo menos 6 horas de luz solar direta por dia.",
        irrigacao:"Mantenha o solo uniformemente úmido, especialmente durante os primeiros anos após o plantio. Evite o encharcamento, pois pode levar a problemas de raiz.", adubacao:" Use um fertilizante balanceado (10-10-10) ou um fertilizante específico para árvores frutíferas. Adubos ricos em fósforo são ideais para incentivar a floração.", curiosidade:"As cerejeiras são amplamente cultivadas como árvores ornamentais em jardins e parques, especialmente no Japão, onde o Hanami (observação das flores de cerejeira) é uma tradição cultural. Além disso, as cerejas são cultivadas comercialmente para produção de frutas."
      },

      {id: 24, imagem: 'https://i.pinimg.com/564x/07/1d/d4/071dd4c35893592985a483907f77c7b1.jpg', nome:'Árvore de Jacarandá', origem:'O jacarandá é nativo da América do Sul, especialmente do Brasil e Argentina. É conhecido por suas flores roxas vibrantes que aparecem na primavera', categoria: 'Arvore', solo:"Prefere solos bem drenados, férteis e ligeiramente ácidos a neutros (pH 6.0 a 7.5). Melhorar o solo com matéria orgânica, como composto, pode ser benéfico.", localizacao:"Plante em um local que receba pleno sol para obter a melhor floração. O jacarandá precisa de pelo menos 6 horas de luz solar direta por dia.",
        irrigacao:"Mantenha o solo uniformemente úmido, especialmente durante os primeiros anos após o plantio. Uma vez estabelecido, o jacarandá é bastante tolerante à seca, mas a irrigação regular durante períodos secos é benéfica.", adubacao:"Use um fertilizante balanceado (10-10-10) ou específico para árvores floríferas. Adubos ricos em fósforo são ideais para incentivar a floração.", curiosidade:"Produzem cápsulas lenhosas que contêm sementes aladas. As cápsulas são planas e arredondadas, e frequentemente permanecem na árvore durante o inverno."
      },

      {id: 25, imagem: 'https://hmjardins.com.br/tok/wp-content/uploads/2018/07/1.jpg', nome:'Árvore de Oliveira', origem:'A oliveira é nativa da região do Mediterrâneo, incluindo países como Grécia, Itália e Espanha. É cultivada há milhares de anos por seus frutos e azeite', categoria: 'Arvore', solo:'Prefere solos bem drenados, férteis e ligeiramente alcalinos (pH 7.0 a 8.5). Pode tolerar solos pobres e rochosos, desde que tenham boa drenagem.', localizacao:'Plante em um local que receba pleno sol, essencial para a produção de frutos. A oliveira necessita de pelo menos 6 a 8 horas de luz solar direta por dia.',
        irrigacao:'As oliveiras são bastante tolerantes à seca uma vez estabelecidas. No entanto, a irrigação regular durante os primeiros anos após o plantio é importante para o desenvolvimento das raízes. Durante períodos de seca prolongada, uma irrigação profunda pode beneficiar a produção de frutos.', adubacao:"Use um fertilizante balanceado (10-10-10) ou específico para árvores frutíferas. Adubos ricos em potássio e fósforo são ideais para incentivar a frutificação.", curiosidade:"As oliveiras são amplamente cultivadas para a produção de azeitonas e azeite. Além disso, são utilizadas como árvores ornamentais, as folhas são estreitas, lanceoladas e verde-acinzentadas, com uma textura coriácea e uma coloração prateada na parte inferior."
      },

      {id: 26, imagem: 'https://http2.mlstatic.com/D_NQ_NP_625819-MLA73415631317_122023-O.webp', nome:'Árvore de Hibisco', origem:'O hibisco é nativo de regiões tropicais e subtropicais ao redor do mundo, especialmente do sudeste da Ásia. É valorizado por suas grandes e vistosas flores', categoria: 'Arvore', solo:"Prefere solos bem drenados, férteis e ligeiramente ácidos a neutros (pH 6.0 a 7.0). Melhorar o solo com matéria orgânica, como composto, pode ser benéfico.",
        localizacao:"Plante em um local que receba pleno sol para obter a melhor floração. O hibisco precisa de pelo menos 6 horas de luz solar direta por dia.", irrigacao:" Mantenha o solo uniformemente úmido, especialmente durante os primeiros anos após o plantio. Durante períodos de seca, uma irrigação profunda pode beneficiar a planta.", adubacao:"Use um fertilizante balanceado (10-10-10) ou específico para plantas floríferas. Adubos ricos em fósforo são ideais para incentivar a floração.", curiosidade:"Os hibiscos são amplamente cultivados como plantas ornamentais em jardins e paisagens. Além disso, algumas espécies são usadas na produção de chá (como o hibisco sabdariffa), e as flores e folhas têm usos medicinais."
      },

      {id: 27, imagem: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhHtqAudD7BqaCxqM6KE-IX8r-cnIyLB6QD4ft0r_m6_ZAaE0JrjT7yUL1zNQFvmHY2G9k02xoT8JvKZupRMb0omcY_2-CNhbQ-GEUpgMNopnzs8YbjTckiQD_YX9ifyBMGVHBfVGtzg7o/s280/palmatum4.jpg', nome:'Árvore de Ácer Japonês', origem:'O ácer japonês é nativo do Japão, Coreia e China. É muito popular em jardins por suas folhas delicadas e cores brilhantes no outono', categoria: 'Arvore', solo:"Prefere solos bem drenados, férteis e ligeiramente ácidos a neutros (pH 5.5 a 6.5). Melhorar o solo com matéria orgânica, como composto, pode ser benéfico.", localizacao:"Plante em um local que receba sol parcial a sombra filtrada. Em climas mais quentes, é importante proteger a árvore do sol intenso da tarde para evitar queimaduras nas folhas.",
        irrigacao:"Mantenha o solo uniformemente úmido, especialmente durante os primeiros anos após o plantio. Evite o encharcamento, que pode levar a problemas de raiz.", adubacao:"Use um fertilizante balanceado (10-10-10) ou específico para árvores ornamentais. Adubos ricos em nitrogênio são ideais para promover o crescimento das folhas.", curiosidade:"As folhas são palmadas e delicadas, com lobos profundos, variando em cor do verde claro ao vermelho brilhante, especialmente no outono, as flores são pequenas, de cor vermelha ou púrpura, e aparecem em cachos no início da primavera, e elas produzem frutos alados, chamados sâmaras, que se dispersam pelo vento."
      },

    {id: 28, imagem: 'https://imagens.reformaagraria.pt/loja-agricola/produtos/grandes/4792-6680-1659729276.jpg', nome:'Árvore de Laranjeira', origem:'A laranjeira é nativa do sudeste asiático, incluindo a Índia e o Vietnã. Foi levada para a Europa pelos árabes e é amplamente cultivada por seus frutos doces', categoria: 'Arvore', solo:" Prefere solos bem drenados, férteis e ligeiramente ácidos a neutros (pH 6.0 a 7.0). Melhorar o solo com matéria orgânica, como composto, pode ser benéfico.", localizacao:"Plante em um local que receba pleno sol para obter a melhor frutificação. A laranjeira necessita de pelo menos 6 a 8 horas de luz solar direta por dia.",
      irrigacao:"Mantenha o solo uniformemente úmido, especialmente durante os primeiros anos após o plantio. Evite o encharcamento, que pode levar a problemas de raiz. Durante períodos de seca prolongada, uma irrigação profunda pode beneficiar a produção de frutos.", adubacao:"Use um fertilizante balanceado (10-10-10) ou específico para árvores frutíferas. Adubos ricos em potássio e fósforo são ideais para incentivar a frutificação.", curiosidade:" As laranjeiras são amplamente cultivadas para a produção de laranjas, usadas tanto para consumo direto quanto para a produção de sucos, doces e outros produtos alimentícios. Além disso, são utilizadas como árvores ornamentais em jardins e paisagens, valorizadas por sua folhagem verde brilhante e flores perfumadas."
    },

      {id: 29, imagem: 'https://furnitstore.com.br/storage/customers/538a5a3a8e723.jpg', nome:'Árvore de Camélia', origem:'As camélias são nativas do leste da Ásia, particularmente da China e Japão. São valorizadas por suas flores vistosas que aparecem no inverno e na primavera', categoria: 'Arvore', solo:"Prefere solos bem drenados, ácidos a ligeiramente ácidos (pH 5.5 a 6.5). Melhorar o solo com matéria orgânica, como composto ou turfa, pode ser benéfico.", localizacao:"Plante em um local que receba sol parcial a sombra filtrada. As camélias prosperam em locais protegidos do sol intenso da tarde, que pode queimar as folhas.",
        irrigacao:"Mantenha o solo uniformemente úmido, especialmente durante os períodos de crescimento ativo e floração. Evite o encharcamento, que pode levar a problemas de raiz.", adubacao:"Use um fertilizante balanceado ou específico para plantas acidófilas (como as azaleias e rododendros). Fertilizantes ricos em nitrogênio são ideais para promover o crescimento das folhas, enquanto o fósforo é importante para a floração.", curiosidade:"As camélias são amplamente cultivadas como plantas ornamentais em jardins e paisagens, valorizadas por suas flores deslumbrantes e folhagem verde brilhante. Elas também são cultivadas para a produção de chá (Camellia sinensis)."
      },

      {id: 30, imagem: 'https://i.pinimg.com/236x/49/32/81/493281629e7dc377104cc56f5d9b75f5.jpg', nome:'Árvore de Acerola', origem:'A acerola é nativa das regiões tropicais das Américas, especialmente das Antilhas e da América Central. É conhecida por seus frutos vermelhos ricos em vitamina C', categoria: 'Arvore', solo:"Prefere solos bem drenados, férteis e ligeiramente ácidos a neutros (pH 6.0 a 7.0). Melhorar o solo com matéria orgânica, como composto, pode ser benéfico.", localizacao:"Plante em um local que receba pleno sol para obter a melhor frutificação. A aceroleira necessita de pelo menos 6 a 8 horas de luz solar direta por dia.",
        irrigacao:"Mantenha o solo uniformemente úmido, especialmente durante os primeiros anos após o plantio. Evite o encharcamento, que pode levar a problemas de raiz. Durante períodos de seca prolongada, uma irrigação profunda pode beneficiar a produção de frutos.", adubacao:"Use um fertilizante balanceado (10-10-10) ou específico para árvores frutíferas. Adubos ricos em potássio e fósforo são ideais para incentivar a frutificação.", curiosidade:" As aceroleiras são amplamente cultivadas para a produção de acerolas, consumidas frescas, em sucos, geleias e outros produtos alimentícios. Além disso, são utilizadas como árvores ornamentais em jardins e paisagens, valorizadas por sua folhagem verde brilhante e flores atraentes."
      }
];

// Rota para a rota raiz '/'
app.get('/', (req, res) => {
  res.json(Flora); // Retorna os dados das flores como JSON
});

// Inicia o servidor na porta especificada ou na porta 3000
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Servidor está rodando na porta ${PORT}`);
});
